import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Same options as scripts/build-edge.mjs (kept in sync by this test failing otherwise).
const ROOT = join(__dirname, '..', '..', '..');

describe('edge function bundle', () => {
  it('supabase/functions/_shared/recompute.js is up to date with the engine (run `npm run build:edge`)', async () => {
    const result = await build({
      absWorkingDir: ROOT,
      entryPoints: ['src/server/recompute.ts'],
      outfile: 'supabase/functions/_shared/recompute.js',
      bundle: true,
      format: 'esm',
      platform: 'neutral',
      target: 'es2022',
      tsconfig: 'tsconfig.json',
      legalComments: 'none',
      banner: { js: '// GENERATED by scripts/build-edge.mjs from src/server/recompute.ts. Do not edit; rebuild instead.' },
      write: false,
      logLevel: 'silent',
    });
    const fresh = result.outputFiles[0].text;
    const committed = readFileSync(join(ROOT, 'supabase/functions/_shared/recompute.js'), 'utf8');
    expect(committed === fresh).toBe(true);
  });
});
