// Bundles src/server/recompute.ts (and the engine + config it imports) into a
// single ESM file the recompute-xp Edge Function can import, so the server
// scores XP with exactly the app's rules.
//   node scripts/build-edge.mjs
import { build } from 'esbuild';

await build({
  entryPoints: ['src/server/recompute.ts'],
  outfile: 'supabase/functions/_shared/recompute.js',
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  tsconfig: 'tsconfig.json', // resolves the @/ and @config/ path aliases
  legalComments: 'none',
  banner: { js: '// GENERATED by scripts/build-edge.mjs from src/server/recompute.ts. Do not edit; rebuild instead.' },
  logLevel: 'info',
});
// src/server/__tests__/bundle.test.ts rebuilds with the same options and fails if the committed file is stale.
